In [44]:
import numpy as np

y_predicted = np.array([1,1,0,0,1])
y_truth = np.array([0.30,0.7,1,0,0.5])

In [45]:
def mae(y_truth,y_predicted):
  total_error = 0
  for yt,yp in zip(y_truth,y_predicted):
    print(yt,yp)

In [46]:
mae(y_truth,y_predicted)

0.3 1
0.7 1
1.0 0
0.0 0
0.5 1


In [47]:
def mae(y_truth,y_predicted):
  total_error = 0
  for yt,yp in zip(y_truth,y_predicted):
    total_error +=abs(yt-yp) # Absolute error
  print("Total_error:" ,total_error)

  mae = total_error/len(y_truth)
  print("MAE:" ,mae)
  return mae


In [48]:
mae(y_truth,y_predicted)

Total_error: 2.5
MAE: 0.5


0.5

In [49]:
y_predicted = np.array([1, 1, 0, 0, 1])
y_truth = np.array([0.30, 0.7, 1, 0, 0.5])

y_predicted -y_truth

array([ 0.7,  0.3, -1. ,  0. ,  0.5])

In [50]:
absolute = np.abs(y_predicted - y_truth)
print("Absolute :", absolute)

Absolute : [0.7 0.3 1.  0.  0.5]


In [51]:
MAE = np.mean(np.abs(y_predicted - y_truth))
print("MAE : ", MAE)

MAE :  0.5


In [52]:
np.log(0.000000000001)

-27.631021115928547

In [53]:
epsilon = 1e-15

In [54]:
y_predicted

array([1, 1, 0, 0, 1])

In [55]:
y_predicted_new = [max(i,epsilon) for i in y_predicted]
y_predicted_new

[1, 1, 1e-15, 1e-15, 1]

In [56]:
1-epsilon

0.999999999999999

In [57]:
y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
y_predicted_new

[0.999999999999999, 0.999999999999999, 1e-15, 1e-15, 0.999999999999999]

In [65]:
np.log(y_predicted_new)

array([-9.99200722e-16, -9.99200722e-16, -3.45387764e+01, -3.45387764e+01,
       -9.99200722e-16])

In [70]:
y_predicted_new = np.array(y_predicted_new)  # Convert y_predicted_new to a NumPy array
-np.mean(y_truth*np.log(y_predicted_new)+(1-y_truth)*np.log(1-y_predicted_new))

17.2696280766844

In [66]:
def log_loss(y_truth, y_predicted):
    y_predicted_new = [max(i,epsilon) for i in y_predicted]
    y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
    y_predicted_new = np.array(y_predicted_new)
    return -np.mean(y_truth*np.log(y_predicted_new)+(1-y_truth)*np.log(1-y_predicted_new))

In [67]:
log_loss(y_truth, y_predicted)

17.2696280766844